title: M. Aji Husein Al Habib
logo: assets/img/20231025_131915.png
#description: text below image
show_downloads: false
theme: jekyll-theme-midnight
<meta name="description" CONTENT="Teacher, Computer Linux and AOSP Enthusiast, Bachelor of Education.">
